name: .NET

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndUnitTest:
    name: push to staging
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://github.com/Norrlandsk/SalarySystem/tree/staging
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET (build)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit test
      run: dotnet test --verbosity normal --no-build
      working-directory: ./../../SalarySystemTests/UnitTests/AccountAuthenticationTests.cs
      
      
  unitTestAndIntegrationTest:
    name: pull request to production
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/Norrlandsk/SalarySystem/tree/master
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET (test)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Unit test
      run: dotnet test --verbosity normal
      working-directory: ./../../SalarySystemTests/UnitTests
    - name: Integration test
      run: dotnet test --verbosity normal --no-build
      working-directory: ./../../SalarySystemTests/IntegrationTests
      
