name: .NET

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: push to staging and build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://github.com/Norrlandsk/SalarySystem/tree/staging
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET (build)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  test:
    name: pull request to production and test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/Norrlandsk/SalarySystem/tree/master
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET (test)
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet test --verbosity normal
      
